version: '3.9'

services:

  express:
    image: expressimage
    container_name: expressserver
    build: ./
    restart: always
    ports:
      - "3000:3000"

  postgres:
    image: postgres:14.5-alpine
    container_name: postgresserver
    restart: always
    ports:
      - "5432:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=storyman
      - POSTGRES_PASSWORD=storyman
      - POSTGRES_DB=umi
      - LANG=es_PE.utf8
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata:
